# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 06:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='地址编号')),
                ('recv_name', models.CharField(max_length=255, verbose_name='收货人姓名')),
                ('recv_phone', models.CharField(max_length=50, verbose_name='收货人联系方式')),
                ('native', models.CharField(max_length=255, verbose_name='国家')),
                ('province', models.CharField(max_length=255, verbose_name='省区')),
                ('city', models.CharField(max_length=255, verbose_name='市区')),
                ('country', models.CharField(max_length=255, verbose_name='县区')),
                ('street', models.CharField(max_length=255, verbose_name='街道')),
                ('desc', models.CharField(max_length=255, verbose_name='详细描述')),
                ('status', models.BooleanField(default=True, verbose_name='是否默认地址')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
    ]
