# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='类型主键')),
                ('gt_name', models.CharField(max_length=255, verbose_name='类型名称')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='static/images/GoodsType/', verbose_name='图片')),
                ('gt_desc', tinymce.models.HTMLField(max_length=255, verbose_name='类型描述')),
                ('null', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoodsType.GoodsType')),
            ],
        ),
    ]
