# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 08:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单编号')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('users', models.CharField(max_length=255, verbose_name='收货人')),
                ('recv_address', models.CharField(max_length=255, verbose_name='收货地址')),
                ('recv_phone', models.CharField(max_length=50, verbose_name='联系方式')),
                ('totale', models.IntegerField(verbose_name='总计金额')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
    ]
