# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 06:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户编号')),
                ('mickname', models.CharField(max_length=255, unique=True, verbose_name='用户昵称')),
                ('age', models.CharField(max_length=200, verbose_name='用户年龄')),
                ('gender', models.CharField(max_length=50, verbose_name='用户性别')),
                ('feader', models.ImageField(default='static/images/User_header/default.jpg', upload_to='static/images/User_header/', verbose_name='用户头像')),
                ('phone', models.CharField(max_length=50, verbose_name='联系方式')),
                ('user', models.OneToOneField(on_delete=models.Model, to=settings.AUTH_USER_MODEL, verbose_name='关联')),
            ],
        ),
    ]
